### ADDRESS
### GET ADDRESSLIST
GET http://localhost:8080/api/addresses


### GET ADDRESSDETAIL
GET http://localhost:8080/api/addresses/{address-id}

### POST ORDER
POST http://localhost:8080/api/orders
Content-Type: application/json


{
      "userPostcode" : "12345",
      "userAddress1": "서울시 광화문",
      "userAddress2": "ㅁㅁ동"
}

### PATCH ADDRESS
PATCH http://localhost:8080/api/orders/{address-id}
Content-Type: application/json



### DELETE ADDRESS
DELETE http://localhost:8080/api/orders/{address-id}
