### GET PAYMENTDETAIL
GET http://localhost:8080/api/payment/{payment-id}


### POST PAYMENT
POST http://localhost:8080/api/payment
Content-Type: application/json


{
  "orderId":"13e6816a-a952-497a-87a5-f85ebc4465ac",
  "paymentType":"카드"
}

### PATCH PAYMENT
PATCH http://localhost:8080/api/payment/{payment-id}
Content-Type: application/json


### DELETE PAYMENT
DELETE http://localhost:8080/api/payment/{payment-id}
