### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA

### POST User Signup
POST http://localhost:8080/api/auth/signup
Content-Type: application/json

{
    "username": "user1",
    "password": "Password1!",
    "email": "email1@email.com",
    "nickname": "myuser"
}

### POST User Signin
POST http://localhost:8080/api/auth/signin
Content-Type: application/json

{
  "username": "user1",
  "password": "Password1!"
}

### UPDATE User Info
PATCH http://localhost:8080/api/auth
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJ0ZWFtMzAiLCJpYXQiOjE3Mzk5MjYzMjUsImV4cCI6MTczOTkzMzUyNSwic3ViIjoidXNlcjEiLCJpZCI6MSwiYXV0aG9yaXRpZXMiOlsiUk9MRV9DVVNUT01FUiJdfQ.iporF-r3pdCW4R1p7ilJuT8_h_DVbQ8MG_04GXIw2UU

{
  "email": "email1@email.com",
  "nickname": "myuser",
  "isPublic": true
}

### DELETE User
DELETE http://localhost:8080/api/auth
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJ0ZWFtMzAiLCJpYXQiOjE3Mzk5MjYzMjUsImV4cCI6MTczOTkzMzUyNSwic3ViIjoidXNlcjEiLCJpZCI6MSwiYXV0aG9yaXRpZXMiOlsiUk9MRV9DVVNUT01FUiJdfQ.iporF-r3pdCW4R1p7ilJuT8_h_DVbQ8MG_04GXIw2UU

{
  "password": "Password1!"
}