### POST User Signup
POST http://localhost:8080/api/auth/signup
Content-Type: application/json

{
    "username": "user1",
    "password": "Password1!",
    "email": "email1@email.com",
    "nickname": "myuser"
}

### POST User Signin
POST http://localhost:8080/api/auth/signin
Content-Type: application/json

{
  "username": "user1",
  "password": "Password1!"
}

### PATCH User Role to OWNER
PATCH http://localhost:8080/api/auth/roles/owner
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJ0ZWFtMzAiLCJpYXQiOjE3NDAxMTU2ODYsImV4cCI6MTc0MDEyMjg4Niwic3ViIjoidXNlcjEiLCJpZCI6MSwiYXV0aG9yaXRpZXMiOlsiUk9MRV9DVVNUT01FUiJdfQ.IthsD9_QOpKfPulodVuqwH1zX2YG4MVTxKZVIU3k6o4

{
  "businessNumber": "11223344166"
}

### PATCH User Role to MANAGER
PATCH http://localhost:8080/api/auth/roles/manager
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJ0ZWFtMzAiLCJpYXQiOjE3NDAxMTU0NDQsImV4cCI6MTc0MDEyMjY0NCwic3ViIjoidXNlcjEiLCJpZCI6MSwiYXV0aG9yaXRpZXMiOlsiUk9MRV9DVVNUT01FUiJdfQ.ePVdWxFC7MSMo56ZbQkEHjQaTUACbdUqGE_m5TbTSek

{
  "secretCode": "7Ius7ZmUM+q4sCAzMOyhsCDrp6Tri4jsoIA="
}

### PATCH User Role to MASTER
PATCH http://localhost:8080/api/auth/roles/master
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJ0ZWFtMzAiLCJpYXQiOjE3NDAxMTUzMzYsImV4cCI6MTc0MDEyMjUzNiwic3ViIjoidXNlcjEiLCJpZCI6MSwiYXV0aG9yaXRpZXMiOlsiUk9MRV9DVVNUT01FUiJdfQ.a-IL2WybH-nHxVsHwMI1Na5qfFZhWdp_yi0LsOyj_EQ

{
  "secretCode": "7Ius7ZmUM+q4sCAzMOyhsCDrp4jsiqTthLA="
}

### GET User Info
GET http://localhost:8080/api/auth/info
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJ0ZWFtMzAiLCJpYXQiOjE3NDA0NjYzNDksImV4cCI6MTc0MDQ3MzU0OSwic3ViIjoidXNlcjEiLCJpZCI6MSwiYXV0aG9yaXRpZXMiOlsiUk9MRV9DVVNUT01FUiJdfQ.CUTwJIW47Z7Ma-WGIIYc_Uxj1otDCPZ4ZE0yBfVD9LY

### PATCH User Info
PATCH http://localhost:8080/api/auth
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJ0ZWFtMzAiLCJpYXQiOjE3NDA0NDgwMjYsImV4cCI6MTc0MDQ1NTIyNiwic3ViIjoidXNlcjEiLCJpZCI6MSwiYXV0aG9yaXRpZXMiOlsiUk9MRV9DVVNUT01FUiJdfQ.UXXIg_LUUBnTgyZLiura2vr-v_ddFgFiWbuvxQswdxM

{
  "email": "email2@email.com",
  "nickname": "myuser123",
  "isPublic": false
}

### DELETE User
DELETE http://localhost:8080/api/auth
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJ0ZWFtMzAiLCJpYXQiOjE3NDA0NDgwMjYsImV4cCI6MTc0MDQ1NTIyNiwic3ViIjoidXNlcjEiLCJpZCI6MSwiYXV0aG9yaXRpZXMiOlsiUk9MRV9DVVNUT01FUiJdfQ.UXXIg_LUUBnTgyZLiura2vr-v_ddFgFiWbuvxQswdxM

{
  "password": "Password1!"
}